export default{
    products: [
        {
            _id:  '1',
            name: 'gaming console 1',
            category: 'Gaming',
            image:'/images/product-1.jpg',
            price: 100000,
            brand: 'motocombat',
            rating: 4.5,
            numReviews: 10,
            countInStock:6,
        },
        {
            _id:  '2',
            name: 'gaming console 1',
            category: 'Gaming',
            image:'/images/product-2.jpg',
            price: 100000,
            brand: 'motocombat',
            rating: 3,
            numReviews: 10,
            countInStock:6,
        },
        {
            _id:  '3',
            name: 'gaming console 1',
            category: 'Gaming',
            image:'/images/product-3.jpg',
            price: 100000,
            brand: 'motocombat',
            rating: 3,
            numReviews: 10,
            countInStock:6,
        },
        {
            _id:  '4',
            name: 'gaming console 1',
            category: 'Gaming',
            image:'/images/product-5.jpg',
            price: 100000,
            brand: 'motocombat',
            rating: 3,
            numReviews: 10,
            countInStock:6,
        },
        {
            _id:  '5',
            name: 'gaming console 1',
            category: 'Gaming',
            image:'/images/product-1.jpg',
            price: 100000,
            brand: 'motocombat',
            rating: 3,
            numReviews: 10,
            countInStock:6,
        },
    ],
};
